version: '3'
services:
  auth:
    build:
      context: ./auth
    ports: 
      - '8000:8080'
    depends_on:
      - auth_db
  auth_db:
    image: postgres:latest
    user: postgres
    env_file:
      - 'auth/.env'
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER} 
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
volumes:
  auth_pgdata:
