[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
async-trait = "0.1.73"
thiserror = "1.0.50"

[lib]
name = "core"
path = "domain/lib.rs"

[[bin]]
name = "web_api"
path = "web_api/main.rs"
